name: Build Pkgs

on:
  workflow_dispatch:

jobs:
  build-pkg:
    runs-on: ubuntu-20.04
    steps:
      - uses: Ste74/build-pkgs@main
        with:
#          gitlab-user: ${{ secrets.gitlab_user }}
#          gitlab-pw: ${{ secrets.gitlab_server_user }}
          user-mail: ${{ secrets.manjaro_mail }}
          build-mirror: ${{ secrets.BUILD_MIRROR }}
          branch: "unstable"
          bump-kernel: false
          bump-modules: "none"
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          boxit-host: ${{ secrets.BOXIT_HOST }}
          boxit-target: ${{ secrets.BOXIT_TARGET }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
